# Generated by Django 3.2.5 on 2022-09-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
