# Generated by Django 3.2.5 on 2022-08-30 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('video_link', embed_video.fields.EmbedVideoField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_aurthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
