# Generated by Django 3.2.5 on 2022-09-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_categories_options'),
        ('home', '0005_comment_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_video', to='config.categories'),
        ),
    ]
