# Generated by Django 3.2.5 on 2022-09-08 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_categories_options'),
        ('home', '0009_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, null=True)),
                ('image', models.ImageField(upload_to='gallery/images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name_plural': 'Features'},
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('teams', models.CharField(max_length=224)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.categories')),
            ],
        ),
    ]
