# Generated by Django 3.2.5 on 2022-09-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220908_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, null=True)),
                ('description', models.CharField(max_length=225, null=True)),
                ('image', models.ImageField(upload_to='athelete/images/')),
            ],
        ),
    ]
