# Generated by Django 3.2.5 on 2022-09-08 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_categories_options'),
        ('home', '0012_athelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='athelete',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athelete',
            name='dob',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='athelete',
            name='firstgame',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='athelete',
            name='participants',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='athelete',
            name='team',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athelete',
            name='description',
            field=models.TextField(max_length=225, null=True),
        ),
    ]
