# Generated by Django 3.2.5 on 2022-09-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
