# Generated by Django 3.2.5 on 2022-09-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
    ]
