# Generated by Django 3.2.5 on 2022-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='video/%y')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
