# Generated by Django 3.2.5 on 2022-09-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='athelete',
            name='is_liked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
