# Generated by Django 3.2.5 on 2022-09-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_athelete_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevideo',
            name='image',
            field=models.ImageField(null=True, upload_to='news/'),
        ),
    ]
